@startuml LTE
title LTE seaquence
UE <-- eNB: PSS(Primary Syncronization Signal)
UE <-- eNB: SSS(Secondary Syncronization Signal)
UE <-- eNB: MIB(Master Information Block)
UE <-- eNB: SIB1(System Information Block type 1)
UE <-- eNB: SIB2(System Information Block type 2)
UE -> eNB: RRC Connection Request
UE <-- eNB: RRC Connection Setup
UE -> eNB: RRC Connection Setup Compleate + Attach Request (ESM:PDN Connectivity Request)
UE <-- eNB: Identity Request
UE -> eNB: Identity Response
UE <-- eNB: UE Capability Request
UE -> eNB: UE Capability Response
UE <-- eNB: Authentication Request
UE -> eNB: Authentication Response
UE <-- eNB: Security Mode Command
UE -> eNB: Security Mode Complete
UE <-- eNB: ESM Information Request
UE -> eNB: ESM Information Response
UE <-- eNB: Attach Accept + Activate Default EPS Bearer 
UE -> eNB: Activate Default EPS Bearer Accept
UE -> eNB: Attach Complete


@enduml